#Welcome to the Config file for Javelin Plugin. Here you can customise everything about the plugin.

## Do support the plugin by leaving a review on SpigotMC or Modrinth. It will help me a lot. Thank you!

## Need any help, Join my Discord https://discord.gg/vUHMxPvege  🔥

# Unit of distance | Default: Blocks | Options: Blocks, Meters
Unit: 'Blocks'