name: Javelin
version: '1.2'
main: me.hellofaizan.javelin.Javelin
api-version: '1.21'
load: STARTUP
authors: [ HelloFaizan ]
description: Javelin throw in Minecraft
website: https://hellofaizan.me
commands:
  javelinlb:
    description: Display the Javelin throw leaderboard
    usage: /javelinlb
    aliases: [jlb, javelin, javelinleaderbaord, leaderboard]
